### ISSUE TITLE
Tests, en general

### ISSUE THREAD

**Issue by delucas** [NewtonGauss/zork#2]
Selecciono este fragmento como ejemplo, pero está por todos lados:
1. No deberían crear los objetos desde JSON en los tests, sino crearlos directamente en forma programática
2. Si van a crear los mismos objetos para cada prueba, lo mejor es utilizar un método marcado con `@Before`, que se ejecuta antes de cada `@Test`.

https://github.com/NewtonGauss/zork/blob/7fa9f5a3b17eb5ed9a18738166fcedaec55f16fd/src/test/comandos/DarComandoTest.java#L17-L19

**Comment by NewtonGauss** [comment]
Solucionado 74b3f1b

**Comment by delucas** [comment]
:+1:
