### ISSUE TITLE
No debe haber JSON en el código

### ISSUE THREAD

**Issue by delucas** [NewtonGauss/zork#5]
Saquen todos los fragmentos de JSON del código fuente. En las pruebas es evidente: deberían crear objetos en lugar de convertir JSON en objetos.
Le quitan legibilidad y reusabilidad.

Adicionalmente, no deberían probar nada que tenga que ver con "GSON convirtió correctamente el JSON a objeto", porque eso depende de la biblioteca externa.

**Comment by NewtonGauss** [comment]
Solucionado 74b3f1b

**Comment by delucas** [comment]
:+1:
