### ISSUE TITLE
Uso de constantes

### ISSUE THREAD

**Issue by delucas** [NewtonGauss/zork#6]
https://github.com/NewtonGauss/zork/blob/7fa9f5a3b17eb5ed9a18738166fcedaec55f16fd/src/zork/Trigger.java#L10-L12

En Java se prefieren los `enum` por encima de las constantes. Nos brindan más flexibilidad.

**Comment by NewtonGauss** [comment]
Enums de tipo de trigger 6fda0bc98727c1898d44dd947b4ff38c586f646c.

**Comment by delucas** [comment]
:+1:
