### ISSUE TITLE
Investigar Decorator

### ISSUE THREAD

**Issue by delucas** [NewtonGauss/zork#8]
https://github.com/NewtonGauss/zork/blob/7fa9f5a3b17eb5ed9a18738166fcedaec55f16fd/src/zork/NPC.java#L82

El uso de métodos estáticos tiende a indicar que estamos dejando la OOP para pasar a algo más estructurado-básico. ¿Por qué no explorar el concepto de Decorator para la articulación de los sustantivos?

Ejemplo de cómo quedaría:

```java
new Articulador(item).toString();
```

**Comment by NewtonGauss** [comment]
Me imagino que esto resuelve el problema: 85aa461e1ee884ee33bdcab1ae8318a9dac6dd91. Me pareció más cómodo ir por el lado de la clase abstracta porque no veo una forma sencilla de utilizar el patrón Decorator en todos las clases que son enumerables (que necesiten articulos).

**Comment by delucas** [comment]
:+1:
